package com.aquatrack.enums;

/**
 * Categories of alerts generated by the AquaTrack alert engine.
 */
public enum AlertType {

    /** Consumption exceeded a pre-configured threshold. */
    HIGH_CONSUMPTION("High Consumption"),

    /** Suspected water leak based on continuous low-flow detection. */
    LEAK_DETECTION("Leak Detection"),

    /** Abnormal usage spike compared to historical average. */
    ABNORMAL_USAGE("Abnormal Usage"),

    /** Meter reading is missing for a billing period. */
    MISSING_READING("Missing Reading"),

    /** Meter reading is lower than the previous reading (reverse flow). */
    NEGATIVE_CONSUMPTION("Negative Consumption"),

    /** Meter device battery or connectivity issue detected. */
    METER_FAULT("Meter Fault"),

    /** Invoice payment is overdue. */
    PAYMENT_OVERDUE("Payment Overdue"),

    /** Bulk water inventory is below the configured minimum threshold. */
    LOW_INVENTORY("Low Inventory"),

    /** System-level alert (e.g. scheduler failure, PDF generation error). */
    SYSTEM("System");

    private final String displayName;
    AlertType(String displayName) { this.displayName = displayName; }
    public String getDisplayName() { return displayName; }
}
