package com.aquatrack.entity.base;

import com.aquatrack.enums.Status;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Abstract base entity providing common audit, lifecycle, and identity fields
 * for every domain entity in AquaTrack.
 *
 * <p>All domain entities MUST extend this class. It provides:
 * <ul>
 *   <li>UUID primary key (generated by the database using gen_random_uuid())</li>
 *   <li>JPA auditing fields (created_at, updated_at, created_by, updated_by)</li>
 *   <li>Optimistic locking via {@code @Version}</li>
 *   <li>Soft delete support via {@code isDeleted} flag</li>
 *   <li>Status lifecycle management via {@code Status} enum</li>
 * </ul>
 * </p>
 *
 * <p>The {@link AuditingEntityListener} is registered here so subclasses
 * automatically get audit population without any additional configuration.</p>
 *
 * @author AquaTrack Engineering Team
 * @version 1.0.0
 * @see AuditingEntityListener
 * @see Status
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
public abstract class BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * UUID primary key. Generated by PostgreSQL's gen_random_uuid() function.
     * Never updated after initial insert.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UUID DEFAULT gen_random_uuid()")
    private UUID id;

    /**
     * Timestamp when this record was first created.
     * Populated automatically by JPA Auditing — never set manually.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this record was last modified.
     * Updated automatically by JPA Auditing on every merge.
     */
    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Username or identifier of the user who created this record.
     * Populated by {@link com.aquatrack.config.AuditConfig#auditorProvider()}.
     */
    @CreatedBy
    @Column(name = "created_by", updatable = false, length = 255)
    private String createdBy;

    /**
     * Username or identifier of the user who last modified this record.
     * Updated by {@link com.aquatrack.config.AuditConfig#auditorProvider()}.
     */
    @LastModifiedBy
    @Column(name = "updated_by", length = 255)
    private String updatedBy;

    /**
     * Optimistic locking version counter.
     * Hibernate increments this on each update. Concurrent modification
     * of the same version throws {@link jakarta.persistence.OptimisticLockException}.
     */
    @Version
    @Column(name = "version", nullable = false)
    private Long version = 0L;

    /**
     * Soft delete flag. When true, this record is logically deleted
     * and must not appear in any business queries.
     *
     * <p>Never perform hard deletes. Always set {@code isDeleted = true}
     * and call {@code save()} instead.</p>
     */
    @Column(name = "is_deleted", nullable = false)
    private Boolean isDeleted = Boolean.FALSE;

    /**
     * Current lifecycle status of this entity.
     * Defaults to {@link Status#ACTIVE} on creation.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    private Status status = Status.ACTIVE;

    /**
     * Performs a soft delete by marking this entity as deleted
     * and setting its status to {@link Status#DELETED}.
     *
     * <p>Call this method instead of using the repository's delete methods.
     * After calling this, persist the entity via {@code save()}.</p>
     */
    public void softDelete() {
        this.isDeleted = Boolean.TRUE;
        this.status = Status.DELETED;
    }

    /**
     * Checks whether this entity is active (not soft-deleted and status is ACTIVE).
     *
     * @return true if the entity is active and not deleted
     */
    public boolean isActive() {
        return Boolean.FALSE.equals(this.isDeleted) && Status.ACTIVE.equals(this.status);
    }

    /**
     * Deactivates this entity by setting its status to {@link Status#INACTIVE}.
     * Does not perform a soft delete — the record remains queryable.
     */
    public void deactivate() {
        this.status = Status.INACTIVE;
    }

    /**
     * Reactivates a previously deactivated entity.
     */
    public void activate() {
        this.status = Status.ACTIVE;
        this.isDeleted = Boolean.FALSE;
    }
}
